# -*- coding: utf-8 -*-
"""machine learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQQv1Nb65UvA7N31abf2UJ2iss3jdri4
"""

import pandas as pd

df2=pd.read_csv("/content/education_career_success.csv")

df2.info()

df2.head()

#step:1

col = df2.columns.tolist()
col

df2["Gender"].unique()

df2["Field_of_Study"].unique()

df2["Current_Job_Level"].unique()

df2["Entrepreneurship"].unique()

df2["Student_ID"].unique()

#changing student_id as index to the df
df2.set_index("Student_ID",inplace=True)

df2.head()

# Replaceing gender column from object to int

df2["Gender"].unique()

df2["Gender"]=df2["Gender"]. map ({"Female" : 0,"Male" : 1,"Other":2})

df2["Gender"].unique()

df2.info()

df2["Current_Job_Level"].unique()

df2["Current_Job_Level"]= df2["Current_Job_Level"].map({"Entry":1,"Mid":2,"Senior":3,"Executive":4})

df2["Current_Job_Level"].unique()

df2.info()

df2["Entrepreneurship"].unique()

df2["Entrepreneurship"] = df2["Entrepreneurship"].map({"Yes":1,"No":0})

df2["Entrepreneurship"].unique()

df2.info()

df2["Field_of_Study"].unique()

from sklearn.preprocessing import OrdinalEncoder

O = OrdinalEncoder()

df2["Field_of_Study"]=O.fit_transform(df2[["Field_of_Study"]])

df2["Field_of_Study"].unique()

df2.info()

df2.corr()